name: macos

on:
  push:
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: appleclang ${{matrix.build-type}}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Clone recursively
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: >
          CC=clang CXX=clang++
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G Ninja
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build -v

      - name: Run
        run: ${{github.workspace}}/build/bin/graphtool test/cytron.dot
